import = ["/home/coderosh/.config/alacritty/tokyonight_night.toml"]

[font]
size = 10

[font.normal]
# family = "FiraCode Nerd Font"
# # family = "JetBrainsMono Nerd Font"
family = "Dank Mono"
style = "Regular"

[window]
dynamic_title = true
opacity = 0.85

[window.padding]
x = 5
y = 0

# [shell]
# program = "/usr/bin/fish"
# args = [ "-c", "tmux attach || tmux" ]
