import = ["/home/coderosh/.config/alacritty/catppuccin_mocha.toml"]

[font]
size = 8

[font.offset]
x = 0
y = 1

[font.normal]
# family = "FiraCode Nerd Font"
# family = "JetBrainsMono Nerd Font"
family = "Dank Mono"
style = "Regular"

[window]
dynamic_title = true
opacity = 0.85
decorations = "none"

[window.padding]
x = 5
y = 0

# [shell]
# program = "/usr/bin/fish"
# args = ["-c", "tmux attach || tmux"]
