[colors.primary]
  background = '0x011627'
  foreground = '0xd6deeb'

[colors.cursor]
  text = '0xffffff'
  cursor = '0x7e57c2'

[colors.normal]
  black = '0x000000'
  red = '0xef5350'
  green = '0x22da6e'
  yellow = '0xaddb67'
  blue = '0x82aaff'
  magenta = '0xc792ea'
  cyan = '0x21c7a8'
  white = '0xffffff'

[colors.bright]
  black = '0x575656'
  red = '0xef5350'
  green = '0x22da6e'
  yellow = '0xffeb95'
  blue = '0x82aaff'
  magenta = '0xc792ea'
  cyan = '0x7fdbca'
  white = '0xffffff'
