#!/usr/bin/env bash

colorschemes=`echo "rosepine_main tokyonight_night catppuccin_mocha nord gruvbox_material_hard_dark" | tr ' ' '\n'`

colorscheme=`printf "$colorschemes" | fzf --border --margin=2 --reverse --header 'Select Colorscheme'`

if [ -z "$colorscheme" ]; then
    echo "Please select a colorscheme"
    exit
fi

echo "Changing colorscheme to: $colorscheme"

if printf $colorscheme | grep -qs $colorscheme; then

  # awesome
  sed -i "s/local colorscheme = colorschemes\.[^ ]*/local colorscheme = colorschemes.$colorscheme/" ~/.config/awesome/themes/colorscheme/init.lua

  # neovim
  sed -i "s/local colorscheme = colorschemes\.[^ ]*/local colorscheme = colorschemes.$colorscheme/" ~/.config/nvim/lua/coderosh/plugins/colorscheme.lua

  # alacritty
  sed -i "s/config\/alacritty\/[^ ]*\.toml/config\/alacritty\/$colorscheme.toml/" ~/.config/alacritty/alacritty.toml

  # tmux
  sed -i "s/config\/tmux\/colorschemes\/[^ ]*\.conf/config\/tmux\/colorschemes\/$colorscheme.conf/" ~/.config/tmux/tmux.conf

  # fish
  sed -i "s/fish_config theme choose [^ ]*/fish_config theme choose \"$colorscheme\"/" ~/.config/fish/config.fish

  # Restart awesome
  awesome-client 'awesome.restart()' 2> /dev/null

  echo "Done"

fi
