#!/usr/bin/env bash

colorschemes=`echo "rosepine_main tokyonight_night catppuccin_mocha" | tr ' ' '\n'`

colorscheme=`printf "$colorschemes" | fzf`

if [ -z "$colorscheme" ]; then
    echo "Please select a colorscheme"
    exit
fi

echo "Changing colorscheme to: $colorscheme"

if printf $colorscheme | grep -qs $colorscheme; then

  # awesome
  sed -i "s/local colorscheme = colorschemes\.[^ ]*/local colorscheme = colorschemes.$colorscheme/" ~/.config/awesome/themes/colorscheme/init.lua

  # neovim
  sed -i "s/local colorscheme = colorschemes\.[^ ]*/local colorscheme = colorschemes.$colorscheme/" ~/.config/nvim/lua/coderosh/plugins/colorscheme.lua

  # alacritty
  sed -i "s/config\/alacritty\/[^ ]*\.yml/config\/alacritty\/$colorscheme.yml/" ~/.config/alacritty/alacritty.yml

  # tmux
  sed -i "s/config\/tmux\/colorschemes\/[^ ]*\.conf/config\/tmux\/colorschemes\/$colorscheme.conf/" ~/.config/tmux/tmux.conf

  # Restart awesome
  awesome-client 'awesome.restart()' 2> /dev/null

  echo "Done"

fi
