#!/usr/bin/env bash

nmcli -f 'bssid,signal,bars,freq,ssid' --color yes device wifi | fzf --border --margin=2 --reverse  --header-lines=1 --ansi --inline-info --with-nth=2.. --bind='enter:execute:nmcli -a device wifi connect {1}'
