#!/bin/bash

extract_username() {
    local url=$1

    if [[ $url == git@* ]]; then
        echo "$url" | awk -F'[:/]' '{print $2}'
    else
        echo "$url" | awk -F'[:/]' '{print $5}'
    fi
}

username=$(extract_username "$1")
directory=$(echo "$HOME/github/$username")

mkdir -p $directory

git -C $directory clone $1
